apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: health-deployment
  labels:
    name: health
spec:
  replicas: 2
  selector:
    matchLabels:
      name: health
  template:
    metadata:
      labels:
        name: health
    spec:
      containers:
        - name: health
          image: kryfitek/health:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          ports:
            - containerPort: 5000
      imagePullSecrets:
      - name: dockerhub