apiVersion: v1
kind: Service
metadata:
  name: health
  namespace: backend
  labels:
    name: health
spec:
  type: ClusterIP
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    name: health
